name: Create VirtualBox disk image from Dockerfile

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'docker/*'
      - '.github/workflows/virtualbox_image.yml'

env:
  VM_PASSWORD: temppwd

jobs:
  virtualbox_image_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [base_python, moab, dagmc, openmc]
        hdf5: ['']
        include:
          - stage: dagmc
            hdf5: _hdf5
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build VirtualBox image using d2vm
        run: |
          curl -sL "https://github.com/linka-cloud/d2vm/releases/download/v0.2.0/d2vm_v0.2.0_linux_amd64.tar.gz" | tar -xvz d2vm
          sudo mv d2vm /usr/local/bin/
          echo "make worked"
          sudo d2vm convert ghcr.io/pyne/pyne_ubuntu_22.04_py3${{ matrix.hdf5 }}/${{ matrix.stage }}:stable -p ${{ env.VM_PASSWORD }} -o pyne.vdi
          